language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "fk5ZsqyDTKnnfFseSykJiuXqhTSbiD59AZCBDxrXo90/kmRTqbOjWUUPKppcDlG8NEd+2AIzL6M+RGh7AanEnRayuSVvp3IwED3XtZJgrDOzSnVM0ZJzFYaO54fYoFtDkOLyN4SwqSf6F878VXgMYZPJ03Q6K2Khhs4jpmFg2Xqxwg/1eJqa/kWO7ByZhoYWkl2+WaKT7COBVcQ/2Dj03j2LAvPvBBJ4Y5rT5Cf8ytcX7pqmdOoqaMXxgtsHS1jnU3wm7zc6MWJY43S0lmq+gggi8mO37ehpQCCOaOmEy3LWrbmY+GWeCYslswtVAJjzAz4skxj24tcyLB3Y5F1qbXeWssdx44ahdHt+VcmD027I73fUo90+j+Qlpd5noPnxvvpkpOwH2g6leLx1u2UA0pGPdF0SvUQ/cVoXlQGAgua3E1a4X50KQPOPW5e0wWlTgRq6vxHVE+3ye6odwMCkzUygy5nHZQ/UWA1BE+qMjkf5GvtpAuF+0Dss+tGEsJISA5WWu3FhiQBfP0KplnHKZLfiAODCXihQMZWbOIODFLIvZ5rNGc5NhGwDUwUhV6HsOjQCwCRGyazZQ9VuTwj+RehZy/pFQnjAG+VehWEplHBFYoh/BrDN0+qPnIIvIpxrx5qJwSP11o/GFlnRH1INwzoMc+vGlocJptKveouxIDM="

addons:
  coverity_scan:
    project:
      name: "nalexandru/NekoEngine"
      description: "Build submitted via Travis CI"
    notification_email: alexandru.naiman@icloud.com
    build_command_prepend: "./Setup.sh && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG .."
    build_command:   "make"
    branch_pattern: coverity_scan

matrix:
 include:
  - os: linux
    sudo: required
    dist: trusty
    compiler: gcc
  - os: linux
    sudo: required
    dist: trusty
    compiler: clang
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode7.3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

before_script:
- ./Setup.sh

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd build; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. && make; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -workspace Projects/Xcode/NekoEngine.xcworkspace -scheme NekoEngine_Travis -configuration Debug; fi
