language: cpp

matrix:
 include:
#  - os: linux
#    sudo: required
#    dist: trusty
#    compiler: gcc
#  - os: linux
#    sudo: required
#    dist: trusty
#    compiler: clang
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode6.4

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://www.cmake.org/files/v3.5/cmake-3.5.0-Linux-x86_64.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xf cmake-3.5.0-Linux-x86_64.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo cp -r cmake-3.5.0-Linux-x86_64/* /usr; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

before_script:
- ./Setup.sh

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd build; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. && make; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -workspace "Neko Engine.xcworkspace" -scheme NekoEngine -configuration Debug; fi
