#ifndef VERSION_H
#define VERSION_H

#define	EDITOR_VERSION_MAJOR	0
#define EDITOR_VERSION_MINOR	3
#define EDITOR_VERSION_REVISION 0
#define EDITOR_VERSION_BUILD	20
#define EDITOR_VERSION_PATCH	0

#define EDITOR_VERSION_STRING   "0.3.0.20"

#endif // VERSION_H
